=== Rogan003/Sajt-za-telefone/sema.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="licneKarte">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="licnaKarta" minOccurs="1" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="osoba" minOccurs="1" maxOccurs="1">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="ime" minOccurs="1" maxOccurs="1" type="xsd:string" />
                                        <xsd:element name="prezime" minOccurs="1" maxOccurs="1" type="xsd:string" />
                                        <xsd:element name="datumRodjenja" minOccurs="1" maxOccurs="1" type="xsd:date" />
                                        <xsd:element name="pol" minOccurs="1" maxOccurs="1">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:enumeration value="M"/>
                                                    <xsd:enumeration value="Z"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element> 
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="dokument" minOccurs="1" maxOccurs="1">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="regBr" minOccurs="1" maxOccurs="1">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:pattern value="([0-9])+" />
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                        <xsd:element name="datumIzdavanja" minOccurs="1" maxOccurs="1" type="xsd:date" />
                                        <xsd:element name="vaziDo" minOccurs="1" maxOccurs="1" type="xsd:date" />
                                        <xsd:element name="dokumentIzdaje" minOccurs="1" maxOccurs="1" type="xsd:string" />
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Rogan003/Sajt-za-telefone/licnakarta.xml
<?xml version="1.0" encoding="UTF-8"?>
<licneKarte xsi:schemaLocation="sema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <licnaKarta>
        <osoba>
            <ime>Esad</ime>
            <prezime>Dzudzo</prezime>
            <datumRodjenja>1958-07-05</datumRodjenja>
            <pol>M</pol>
        </osoba>
        <dokument>
            <regBr>005778960</regBr>
            <datumIzdavanja>2014-08-26</datumIzdavanja>
            <vaziDo>2024-08-26</vaziDo>
            <dokumentIzdaje>PS u Tutinu</dokumentIzdaje>
        </dokument>
    </licnaKarta>
    <licnaKarta>
        <osoba>
            <ime>Milica</ime>
            <prezime>Test</prezime>
            <datumRodjenja>1968-02-29</datumRodjenja>
            <pol>Z</pol>
        </osoba>
        <dokument>
            <regBr>955555546</regBr>
            <datumIzdavanja>2008-07-24</datumIzdavanja>
            <vaziDo>2013-07-24</vaziDo>
            <dokumentIzdaje>PU za grad Beograd</dokumentIzdaje>
        </dokument>
    </licnaKarta>
    <licnaKarta>
        <osoba>
            <ime>Slavisa</ime>
            <prezime>Mijatovic</prezime>
            <datumRodjenja>1975-06-30</datumRodjenja>
            <pol>M</pol>
        </osoba>
        <dokument>
            <regBr>001102408</regBr>
            <datumIzdavanja>2009-10-08</datumIzdavanja>
            <vaziDo>2014-10-08</vaziDo>
            <dokumentIzdaje>PU za grad Beograd</dokumentIzdaje>
        </dokument>
    </licnaKarta>
</licneKarte>
